services:
    nemo_test.notifer: // имя сервиса должно быть уникальным
        class: Nemo\TestBundle\Example // полный путь к классу-сервису
        arguments: ["@service_id", "plain_value", "%parameter%"]
